spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankservice
    username: postgres
    password: 123
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
# Actuator
manangement:
  health:
    status:
      order: FATAL, DOWN, OUT_OF_SERVICE, WARN, UP
      http-mapping:
        WARN: 200
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
    resume:
      enabled: true
    pause:
      enabled: true
    shutdown:
      enabled: true
    configprops:
      keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services,sun.java.command
    env:
      keys-to-sanitize: password,secret,key,token,.*credentials.*,vcap_services,sun.java.command
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
       


# Filter
gui:
  protocol: http
  host: localhost
  port: 3000
  
server:
  servlet:
    context-path: /api
  port: 9090